baseURL = "https://gohugo.io/hugo-blog/public"
title = "软件分享博客"
copyright = "Hqqich"
pagination.pagerSize = 3 # for demonstration of pagination
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
theme = "hugo-theme-tailwind"
enableGitInfo = true

[markup]
  _merge = "deep"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

